#!/bin/zsh
set -eu
file="${@[-1]}"
if [[ " $* " == *' stream=codec_type '* ]]; then
  [[ -s "$file" ]] || exit 1
  IFS= read -r header < "$file"
  [[ "$header" == 'fake compressed'* ]] || exit 1
  print video
elif [[ "${file:t}" == *long* ]]; then
  print 20
else
  print 5
fi
